import numpy as np
import matplotlib.pyplot as plt

# import raw data for the three functions
h1_Re, h1_Im, t_k = np.loadtxt("h1.txt", delimiter = ", ", unpack = True)
h2_Re, h2_Im, t_k = np.loadtxt("h2.txt", delimiter = ", ", unpack = True)
k, t_k, h3_Re, h3_Im = np.loadtxt("h3.txt", delimiter = ", ", unpack = True)
# import final data after DFT and IDFT have been applied
h1__Re, h1__Im, t_k = np.loadtxt("h1_.txt", delimiter = ", ", unpack = True)
h2__Re, h2__Im, t_k = np.loadtxt("h2_.txt", delimiter = ", ", unpack = True)
h3__Re, h3__Im, t_ = np.loadtxt("h3_.txt", delimiter = ", ", unpack = True)

# function h1(t) and h1'(t)
plt.figure(1)
fig, ax1 = plt.subplots()
ax2 = ax1.twinx()
ax1.plot(t_k, h1_Re, 'b-', linewidth=1.5, label = 'Re(h1)')
ax1.plot(t_k, h1__Re, 'r-', linewidth=1.5, label = 'Re(h1\')')
ax2.plot(t_k, h1_Im, 'b--', linewidth=1.5, label = 'Im(h1)')
ax2.plot(t_k, h1__Im, 'r--', linewidth=1.5, label = 'Im(h1\')')
ax1.set_xlabel('t_k')
ax1.set_ylabel('Re(h(t_k))')
ax2.set_ylabel('Im(h(t_k))')
plt.xlim(0, 6.22)
plt.axhline(y=0, color='gray')
ax1.legend(loc='upper left')
ax2.legend(loc='upper right')
plt.savefig("h1.png", dpi=300)

# function h2(t) and h2'(t)
plt.figure(2)
fig, ax1 = plt.subplots()
ax2 = ax1.twinx()
ax1.plot(t_k, h2_Re, 'b-', linewidth=1.5, label = 'Re(h2)')
ax1.plot(t_k, h2__Re, 'r-', linewidth=1.5, label = 'Re(h2\')')
ax2.plot(t_k, h2_Im, 'b--', linewidth=1.5, label = 'Im(h2)')
ax2.plot(t_k, h2__Im, 'r--', linewidth=1.5, label = 'Im(h2\')')
ax1.set_xlabel('t_k')
ax1.set_ylabel('Re(h(t_k))')
ax2.set_ylabel('Im(h(t_k))')
plt.xlim(0, 6.22)
plt.axhline(y=0, color='gray')
ax1.legend(loc='upper left')
ax2.legend(loc='upper right')
plt.savefig("h2.png", dpi=300)

# real parts of h3(t) and h3'(t)
plt.figure(3)
plt.plot(t_, h3_Re, 'b-', linewidth=1.5, label = 'Re(h3)')
plt.plot(t_, h3__Re, 'r-', linewidth=1.5, label = 'Re(h3\')')
plt.xlabel('t_k')
plt.ylabel('Re(h(t_k))')
plt.xlim(0, 6.25)
plt.axhline(y=0, color='gray')
plt.legend(loc='upper right')
plt.savefig("h3_re.png", dpi=300)

# imaginary parts of h3(t) and h3'(t)
plt.figure(4)
plt.plot(t_, h3_Im, 'b--', linewidth=1.5, label = 'Im(h3)')
plt.plot(t_, h3__Im, 'r--', linewidth=1.5, label = 'Im(h3\')')
plt.xlabel('t_k')
plt.ylabel('Im(h(t_k))')
plt.xlim(0, 6.25)
plt.axhline(y=0, color='gray')
plt.legend(loc='upper right')
plt.savefig("h3_im.png", dpi=300)